<?php
/**
 * Implements hook_form_alter().
 */
function sermon_id3_form_alter(&$form, &$form_state, $form_id) {
  //dpm($form_id);
  if ($form_id == 'sermon_node_form') {
    //dpm($form);
    $form['title']['#default_value'] = 'Title will be created from audio file';
  }
}

/**
 * Implements hook_node_submit().
 */
function sermon_id3_node_submit($node, $form, &$form_state) {
  //dpm($node);
  if ($node->type == 'sermon') {
    //dpm($form_state);
    // Get file id from $form_state and use it to load $file object
    $fid = $form_state['input']['field_audio']['und'][0]['fid'];
    //dpm($fid);
    $file = file_load($fid);
    //dpm($file);
    if ($file->type === 'audio') {
      $id3_tags = getid3_analyze_file($file);
      //dpm($id3_tags);
      $node->field_talk_title[LANGUAGE_NONE][0]['value'] = $id3_tags['tags_html']['id3v2']['title'][0];
      $node->field_speaker[LANGUAGE_NONE][0]['value'] = $id3_tags['tags_html']['id3v2']['artist'][0];
      $node->field_series[LANGUAGE_NONE][0]['value'] = $id3_tags['tags_html']['id3v2']['album'][0];
      $node->field_date[LANGUAGE_NONE][0]['value']   = $id3_tags['tags_html']['id3v2']['year'][0];
      //$node->field_year[LANGUAGE_NONE][0]['value']   = $id3_tags['tags_html']['id3v2']['year'][0];
      $node->field_length[LANGUAGE_NONE][0]['value'] = $id3_tags['playtime_string'];
      $node->title = $id3_tags['tags_html']['id3v2']['title'][0] . ' - ' . $id3_tags['tags_html']['id3v2']['artist'][0];
    }
  }
}